object Versions {
  lazy val calibanVersion             = "0.7.4"
  lazy val scalacacheVersion          = "0.28.0"
  lazy val logbackVersion             = "1.2.3"
  lazy val s3MockVersion              = "2.1.18"
  lazy val scalatestVersion           = "3.1.0"
  lazy val mockitoVersion             = "1.13.6"
  lazy val mapDbVersion               = "3.0.8"
  lazy val circeVersion               = "0.13.0"
  lazy val awsDynamoDbVersion         = "1.11.759"
  lazy val zioVersion                 = "1.0.0-RC18-2"
  lazy val enumeratumVersion          = "1.5.15"
  lazy val enumeratumCirceVersion     = "1.5.23"
  lazy val http4sVersion              = "0.21.3"
  lazy val javaJwtVersion             = "3.10.2"
  lazy val jwksRsaVersion             = "0.11.0"
  lazy val testcontainersScalaVersion = "0.32.0"
  lazy val testcontainersVersion      = "1.13.0"
}
